$(document).ready(function(){$(".search-results > li").hover(function(){var li=$(this);
if(!li.hasClass("results-header")&&!li.hasClass("results-footer")){li.addClass("hover");
}},function(){$(this).removeClass("hover");
});
$("input.chkJobBox").click(function(){var checkbox=$(this);
if(checkbox.attr("checked")){checkbox.parent().addClass("selected");
}else{checkbox.parent().removeClass("selected");
}var n=$("input.chkJobBox:checked").length;
$("span.selected-jobs").text(n+(n==1?" job":" jobs")+" selected");
});
$("#DateNavigator").change(function(){var that=$(this);
document.location=that.val();
});
$("#SortMode").change(function(){var that=$(this);
document.location=that.val();
});
$(".more").click(function(e){var dl=$(this).parent();
var a=$(this).find("a");
var dd=$(dl).children("dd.less");
$(dd).toggle();
if($(a).html()=="more"){$(a).html("less");
}else{$(a).html("more");
}e.stopPropagation();
e.preventDefault();
return false;
});
});
SEEK.JobDetailsMetrics={};
SEEK.JobDetailsMetrics.JobApply={pageName:"jobs:job application",channel:"jobs",prop4:"job application",prop6:"jobs:application",eVar42:"",events:"event42"};
SEEK.JobDetailsMetrics.EOIApply={pageName:"jobs:express interest",channel:"jobs",prop4:"express interest",prop6:"jobs:express interest",eVar42:"",events:"event42"};
var popUpWin=null;
var intervalId=null;
function postToController(btn,url,postUrl,jobId){$(btn).hide();
$.get(postUrl,{jobId:jobId},function(data,textStatus){if(eval(data).succeeded){window.location=url;
}});
}function hideApplyButton(btn,screenMsg,url){$(screenMsg).fadeIn();
$(btn).hide();
popUpWindow(btn,screenMsg,url);
}function popUpWindow(btn,screenMsg,url){removePopupWindow();
popUpWin=open(url,"popUpWin");
popUpWin.focus();
intervalId=window.setInterval(function(){checkLinkoutWindow(btn,screenMsg);
},500);
}function removePopupWindow(){if(popUpWin!=null&&popUpWin.closed!=null){try{popUpWin.close();
}catch(e){if(!popUpWin.closed){popUpWin.close();
}}}}function checkLinkoutWindow(btn,screenMsg){try{if(popUpWin!=null&&popUpWin.closed){if(intervalId!=null){$(screenMsg).fadeOut();
$(btn).show();
window.clearInterval(intervalId);
intervalId=null;
}popUpWin=null;
}}catch(e){}}SEEK.Cookie.CookieKey.SavedJobIds="_sj";
SEEK.Cookie.CookieKey.SavedJobsDelimiter=",";
SEEK.SaveJobToCookie=function(jobId){var CookieKey=SEEK.Cookie.CookieKey;
var sjArray=SEEK.GetSavedJobsFromCookie();
if($.inArray(jobId.toString(),sjArray)<0){sjArray.push(jobId);
var newValue=sjArray.join(CookieKey.SavedJobsDelimiter);
var expires=new Date();
expires.setDate(expires.getDate()+365);
SEEK.Cookie.setCookie(CookieKey.SavedJobIds,newValue,undefined,"/",undefined,undefined);
}};
SEEK.RemoveJobFromCookie=function(jobId){var CookieKey=SEEK.Cookie.CookieKey;
var sjArray=SEEK.GetSavedJobsFromCookie();
var idf=$.inArray(jobId.toString(),sjArray);
if(idf>=0){sjArray.splice(idf,1);
var newValue=sjArray.join(CookieKey.SavedJobsDelimiter);
SEEK.Cookie.setCookie(CookieKey.SavedJobIds,newValue,undefined,"/",undefined,undefined);
}};
SEEK.GetSavedJobsFromCookie=function(){var CookieKey=SEEK.Cookie.CookieKey;
var sjCookie=SEEK.Cookie.getCookie(CookieKey.SavedJobIds);
if(sjCookie==null||sjCookie==undefined){sjCookie="";
}return sjCookie.split(CookieKey.SavedJobsDelimiter);
};

define("search.saveJob",["jquery","http","pageConfig","config","knockout"],function($,http,pageConfig,config,knockout){var buttonSelector=".is-shortlist-button";
var reasonJobSaved="Added";
var sendOmniture=function(){var clickEventData={name:"SaveThisJobLink",linkTrackVars:"events",linkTrackEvents:"event44",properties:{events:"event44"}};
s.clickEvent(clickEventData);
};
var refreshShortlistedJobs=function(){var node=$(config.viewSelectors.bodyContainer).get(0);
var context=knockout.contextFor(node);
context.$data.jobs.reloadShortlistedJobs();
};
var saveJob=function(btn){if(!btn.data("jobid")){return;
}var toggleOn=!btn.data("shortlisted");
return http.post({url:pageConfig.saveJobActionUrl,data:{jobId:btn.data("jobid"),toggleOn:toggleOn},success:function(data){if(data.success){sendOmniture();
refreshShortlistedJobs();
}}});
};
var loginComplete=function(btn,promise){pageConfig.isAuthenticated=true;
$.when(saveJob(btn),loadLoginPanel(),removeLighboxLinks()).done(function(){promise.resolve();
});
};
var removeLighboxLinks=function(){$("[data-auth-required='true']").each(function(index,element){$(element).attr("data-auth-required",false);
});
};
var loadLoginPanel=function(){return http.get({url:pageConfig.loginDetailsUrl,success:function(response){$("#Header .mod-nav-login").replaceWith(response);
}});
};
var init=function(){$(document).on("lightbox-success",buttonSelector,function(event,promise){loginComplete($(this),promise);
});
$(document).on("click",buttonSelector,function(e){if(pageConfig.isAuthenticated){saveJob($(this));
}});
};
return{init:init};
});

!function($){function setState(el,state){var d="disabled",$el=$(el),data=$el.data();
state=state+"Text";
data.resetText||$el.data("resetText",$el.html());
$el.html(data[state]||$.fn.button.defaults[state]);
state=="loadingText"?$el.addClass(d).attr(d,d):$el.removeClass(d).removeAttr(d);
}function toggle(el){$(el).toggleClass("active");
}$.fn.button=function(options){return this.each(function(){if(options=="toggle"){return toggle(this);
}options&&setState(this,options);
});
};
$.fn.button.defaults={loadingText:"loading..."};
$(function(){$("body").delegate(".btn[data-toggle]","click",function(){$(this).button("toggle");
});
});
}(window.jQuery||window.ender);

